version: "3.8"

services:
  slotlist-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PRODUCTION_BUILD: "true"
    env_file:
      - ./deployment/portainer/production.env
      - ./.env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - slotlist_logs:/app/logs
    networks:
      - internal
      - npm_proxy

  db:
    image: postgres:9.6.3-alpine
    restart: unless-stopped
    env_file:
      - ./deployment/portainer/production.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge
  npm_proxy:
    external: true
    name: npm_proxy

volumes:
  postgres_data:
  slotlist_logs:
